### PR TITLE
Update list() to [] and dict() to {}

### LINKED ISSUE #132: Python3 performance on empty list and dictionaries
Hi @roaldnefs,

I found this today researching for one pylint issue. You can test the impact of this on `salt-lint`, as there are some `list()` and `dict()` in the code.

```
$ python
Python 3.7.5 (default, Oct 17 2019, 12:16:48) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from timeit import timeit
>>> timeit("[]")
0.02775977800047258
>>> timeit("list()")
0.10766769000110799
>>> timeit("{}")
0.07137581899951329
>>> timeit("dict()")
0.12580753499787534
```

### PR DESCRIPTION
**Pull request by roaldnefs**
Update `list()` to `[]` and `dict()` to `{}` for performance improvement.

Fixes #132.

### CODE REVIEW

**Comment by mjtrangoni** [comment]
@roaldnefs just for fun, can you post here some performance information on this?

**Comment by roaldnefs** [comment]
The improvement isn't really noticeable. I did a couple of test runs on our own states, this are the fastest results.

The `develop` branch:

```console
$ time find . -type f -name "*.sls" | xargs --no-run-if-empty salt-lint

real	0m0,336s
user	0m0,287s
sys	0m0,023s
```
And some test run on this branch:

```console
$ time find . -type f -name "*.sls" | xargs --no-run-if-empty salt-lint

real	0m0,300s
user	0m0,281s
sys	0m0,018s
```

**Comment by mjtrangoni** [comment]
Ok, but I guess it is always faster. It could be more relevant if we add more checks.

**Comment by roaldnefs** [comment]
> Ok, but I guess it is always faster. It could be more relevant if we add more checks.

Yes, and the existing code is also a good example for new contributors.

**Pull request merged**
